#!/bin/bash

# Script to guide updating Render CORS configuration
# This helps you add localhost:4200 to allowed origins for local development

echo "================================================"
echo "Render CORS Configuration Update"
echo "================================================"
echo ""
echo "To enable localhost login, you need to update the"
echo "CORS_ALLOWED_ORIGINS environment variable on Render."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Open Render Dashboard:"
echo "   https://dashboard.render.com"
echo ""
echo "2. Select your web service:"
echo "   bullseye-backend"
echo ""
echo "3. Go to 'Environment' tab"
echo ""
echo "4. Find or add CORS_ALLOWED_ORIGINS variable"
echo ""
echo "5. Set the value to:"
echo "   http://localhost:4200,https://your-app.vercel.app"
echo ""
echo "   (Replace 'your-app' with your actual Vercel domain)"
echo ""
echo "6. Click 'Save Changes'"
echo ""
echo "7. Render will automatically redeploy (~5 minutes)"
echo ""
echo "8. Test localhost login at http://localhost:4200"
echo ""
echo "================================================"
echo "Configuration Example:"
echo "================================================"
echo "Variable Name:  CORS_ALLOWED_ORIGINS"
echo "Value:          http://localhost:4200,https://bullseye-ui.vercel.app"
echo ""
echo "Note: Use comma-separated values, no spaces!"
echo "================================================"
echo ""
echo "After update, all environments will work together! ✅"
echo ""
echo "Frontend (Local):   http://localhost:4200"
echo "Backend (Render):   https://bullseye-backend.onrender.com"
echo "Frontend (Prod):    https://your-app.vercel.app"
echo "================================================"
