-- Table to store all NSE stock metadata
CREATE TABLE IF NOT EXISTS stocks (
    symbol VARCHAR(20) PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    industry VARCHAR(100),
    sector VARCHAR(100),
    isin VARCHAR(20),
    series VARCHAR(10) DEFAULT 'EQ',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_symbol (symbol),
    INDEX idx_company_name (company_name),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table to store live stock prices (cached)
CREATE TABLE IF NOT EXISTS stock_prices (
    symbol VARCHAR(20) PRIMARY KEY,
    price DECIMAL(12, 2),
    open_price DECIMAL(12, 2),
    high DECIMAL(12, 2),
    low DECIMAL(12, 2),
    prev_close DECIMAL(12, 2),
    change_value DECIMAL(12, 2),
    change_percent DECIMAL(8, 3),
    volume BIGINT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol) REFERENCES stocks(symbol) ON DELETE CASCADE,
    INDEX idx_last_updated (last_updated),
    INDEX idx_change_percent (change_percent)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert NSE stocks (popular stocks first, add more as needed)
INSERT INTO stocks (symbol, company_name, industry, sector, isin, is_active) VALUES
-- Top 50 NSE Stocks
('RELIANCE', 'Reliance Industries Ltd', 'Refineries', 'Energy', 'INE002A01018', true),
('TCS', 'Tata Consultancy Services Ltd', 'IT Services & Consulting', 'Technology', 'INE467B01029', true),
('HDFCBANK', 'HDFC Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE040A01034', true),
('INFY', 'Infosys Ltd', 'IT Services & Consulting', 'Technology', 'INE009A01021', true),
('ICICIBANK', 'ICICI Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE090A01021', true),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'FMCG', 'Consumer Goods', 'INE030A01027', true),
('BHARTIARTL', 'Bharti Airtel Ltd', 'Telecom Services', 'Telecom', 'INE397D01024', true),
('SBIN', 'State Bank of India', 'Public Sector Bank', 'Financial Services', 'INE062A01020', true),
('LT', 'Larsen & Toubro Ltd', 'Engineering & Construction', 'Infrastructure', 'INE018A01030', true),
('ITC', 'ITC Ltd', 'FMCG', 'Consumer Goods', 'INE154A01025', true),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE237A01028', true),
('AXISBANK', 'Axis Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE238A01034', true),
('BAJFINANCE', 'Bajaj Finance Ltd', 'NBFC', 'Financial Services', 'INE296A01024', true),
('ASIANPAINT', 'Asian Paints Ltd', 'Paints', 'Consumer Goods', 'INE021A01026', true),
('MARUTI', 'Maruti Suzuki India Ltd', 'Automobile', 'Automobile', 'INE585B01010', true),
('HCLTECH', 'HCL Technologies Ltd', 'IT Services & Consulting', 'Technology', 'INE860A01027', true),
('WIPRO', 'Wipro Ltd', 'IT Services & Consulting', 'Technology', 'INE075A01022', true),
('TATAMOTORS', 'Tata Motors Ltd', 'Automobile', 'Automobile', 'INE155A01022', true),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'Pharmaceuticals', 'Healthcare', 'INE044A01036', true),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'Cement', 'Construction Materials', 'INE481G01011', true),
('TITAN', 'Titan Company Ltd', 'Gems & Jewellery', 'Consumer Goods', 'INE280A01028', true),
('NESTLEIND', 'Nestle India Ltd', 'FMCG', 'Consumer Goods', 'INE239A01024', true),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'Power Transmission', 'Utilities', 'INE752E01010', true),
('NTPC', 'NTPC Ltd', 'Power Generation', 'Utilities', 'INE733E01010', true),
('ONGC', 'Oil & Natural Gas Corporation Ltd', 'Oil Exploration', 'Energy', 'INE213A01029', true),
('ADANIENT', 'Adani Enterprises Ltd', 'Trading', 'Diversified', 'INE423A01024', true),
('ADANIPORTS', 'Adani Ports & Special Economic Zone Ltd', 'Port Services', 'Infrastructure', 'INE742F01042', true),
('COALINDIA', 'Coal India Ltd', 'Coal Mining', 'Energy', 'INE522F01014', true),
('JSWSTEEL', 'JSW Steel Ltd', 'Steel', 'Metals', 'INE019A01038', true),
('TATASTEEL', 'Tata Steel Ltd', 'Steel', 'Metals', 'INE081A01020', true),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'NBFC', 'Financial Services', 'INE918I01018', true),
('TECHM', 'Tech Mahindra Ltd', 'IT Services & Consulting', 'Technology', 'INE669C01036', true),
('DIVISLAB', 'Divi\'s Laboratories Ltd', 'Pharmaceuticals', 'Healthcare', 'INE361B01024', true),
('M&M', 'Mahindra & Mahindra Ltd', 'Automobile', 'Automobile', 'INE101A01026', true),
('HINDALCO', 'Hindalco Industries Ltd', 'Aluminium', 'Metals', 'INE038A01020', true),
('EICHERMOT', 'Eicher Motors Ltd', 'Automobile', 'Automobile', 'INE066A01021', true),
('DRREDDY', 'Dr Reddy\'s Laboratories Ltd', 'Pharmaceuticals', 'Healthcare', 'INE089A01023', true),
('BRITANNIA', 'Britannia Industries Ltd', 'FMCG', 'Consumer Goods', 'INE216A01030', true),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'Hospitals', 'Healthcare', 'INE437A01024', true),
('CIPLA', 'Cipla Ltd', 'Pharmaceuticals', 'Healthcare', 'INE059A01026', true),
('GRASIM', 'Grasim Industries Ltd', 'Cement & Textiles', 'Diversified', 'INE047A01021', true),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'Refineries', 'Energy', 'INE029A01011', true),
('INDUSINDBK', 'IndusInd Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE095A01012', true),
('SHREECEM', 'Shree Cement Ltd', 'Cement', 'Construction Materials', 'INE070A01015', true),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'Automobile', 'Automobile', 'INE158A01026', true),
('TATACONSUM', 'Tata Consumer Products Ltd', 'FMCG', 'Consumer Goods', 'INE192A01025', true),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'Automobile', 'Automobile', 'INE917I01010', true),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'Life Insurance', 'Financial Services', 'INE123W01016', true),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'Life Insurance', 'Financial Services', 'INE795G01014', true),
('TATAPOWER', 'Tata Power Company Ltd', 'Power Generation', 'Utilities', 'INE245A01021', true),

-- More NSE Stocks (Next 50)
('VEDL', 'Vedanta Ltd', 'Mining', 'Metals', 'INE205A01025', true),
('BANKBARODA', 'Bank of Baroda', 'Public Sector Bank', 'Financial Services', 'INE028A01039', true),
('PNB', 'Punjab National Bank', 'Public Sector Bank', 'Financial Services', 'INE160A01022', true),
('IOC', 'Indian Oil Corporation Ltd', 'Refineries', 'Energy', 'INE242A01010', true),
('GODREJCP', 'Godrej Consumer Products Ltd', 'FMCG', 'Consumer Goods', 'INE102D01028', true),
('DLF', 'DLF Ltd', 'Real Estate', 'Real Estate', 'INE271C01023', true),
('PIDILITIND', 'Pidilite Industries Ltd', 'Chemicals', 'Chemicals', 'INE318A01026', true),
('SIEMENS', 'Siemens Ltd', 'Engineering', 'Infrastructure', 'INE003A01024', true),
('ABB', 'ABB India Ltd', 'Engineering', 'Infrastructure', 'INE117A01022', true),
('BOSCHLTD', 'Bosch Ltd', 'Auto Components', 'Automobile', 'INE323A01026', true),
('AMBUJACEM', 'Ambuja Cements Ltd', 'Cement', 'Construction Materials', 'INE079A01024', true),
('ACC', 'ACC Ltd', 'Cement', 'Construction Materials', 'INE012A01025', true),
('GAIL', 'GAIL (India) Ltd', 'Gas Transmission', 'Energy', 'INE129A01019', true),
('INDIGO', '6E', 'Airlines', 'Aviation', 'INE646L01027', true),
('HAVELLS', 'Havells India Ltd', 'Electricals', 'Consumer Goods', 'INE176B01034', true),
('LUPIN', 'Lupin Ltd', 'Pharmaceuticals', 'Healthcare', 'INE326A01037', true),
('MOTHERSON', 'Samvardhana Motherson International Ltd', 'Auto Components', 'Automobile', 'INE775A01035', true),
('BERGEPAINT', 'Berger Paints India Ltd', 'Paints', 'Consumer Goods', 'INE463A01038', true),
('MARICO', 'Marico Ltd', 'FMCG', 'Consumer Goods', 'INE196A01026', true),
('DABUR', 'Dabur India Ltd', 'FMCG', 'Consumer Goods', 'INE016A01026', true),
('COLPAL', 'Colgate-Palmolive (India) Ltd', 'FMCG', 'Consumer Goods', 'INE259A01022', true),
('MCDOWELL-N', 'United Spirits Ltd', 'Beverages', 'Consumer Goods', 'INE854D01024', true),
('UPL', 'UPL Ltd', 'Agrochemicals', 'Chemicals', 'INE628A01036', true),
('TORNTPHARM', 'Torrent Pharmaceuticals Ltd', 'Pharmaceuticals', 'Healthcare', 'INE685A01028', true),
('BIOCON', 'Biocon Ltd', 'Pharmaceuticals', 'Healthcare', 'INE376G01013', true),
('AUROPHARMA', 'Aurobindo Pharma Ltd', 'Pharmaceuticals', 'Healthcare', 'INE406A01037', true),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd', 'Pharmaceuticals', 'Healthcare', 'INE010B01027', true),
('PEL', 'Piramal Enterprises Ltd', 'Pharmaceuticals', 'Healthcare', 'INE140A01024', true),
('MUTHOOTFIN', 'Muthoot Finance Ltd', 'NBFC', 'Financial Services', 'INE414G01012', true),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'NBFC', 'Financial Services', 'INE115A01026', true),
('CHOLAFIN', 'Cholamandalam Investment and Finance Company Ltd', 'NBFC', 'Financial Services', 'INE121A01024', true),
('SBICARD', 'SBI Cards and Payment Services Ltd', 'NBFC', 'Financial Services', 'INE018E01016', true),
('BANDHANBNK', 'Bandhan Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE545U01014', true),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE092T01019', true),
('FEDERALBNK', 'Federal Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE171A01029', true),
('CANBK', 'Canara Bank', 'Public Sector Bank', 'Financial Services', 'INE476A01022', true),
('UNIONBANK', 'Union Bank of India', 'Public Sector Bank', 'Financial Services', 'INE692A01016', true),
('INDHOTEL', 'The Indian Hotels Company Ltd', 'Hotels', 'Hospitality', 'INE053A01029', true),
('BATAINDIA', 'Bata India Ltd', 'Footwear', 'Consumer Goods', 'INE176A01028', true),
('RELAXO', 'Relaxo Footwears Ltd', 'Footwear', 'Consumer Goods', 'INE131B01039', true),
('VOLTAS', 'Voltas Ltd', 'Consumer Durables', 'Consumer Goods', 'INE226A01021', true),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'Consumer Durables', 'Consumer Goods', 'INE716A01013', true),
('Dixon', 'Dixon Technologies (India) Ltd', 'Electronics', 'Consumer Goods', 'INE935N01012', true),
('AMARAJABAT', 'Amara Raja Batteries Ltd', 'Auto Components', 'Automobile', 'INE885A01032', true),
('EXIDEIND', 'Exide Industries Ltd', 'Auto Components', 'Automobile', 'INE302A01020', true),
('MRF', 'MRF Ltd', 'Tyres', 'Automobile', 'INE883A01011', true),
('APOLLOTYRE', 'Apollo Tyres Ltd', 'Tyres', 'Automobile', 'INE438A01022', true),
('CEATLTD', 'CEAT Ltd', 'Tyres', 'Automobile', 'INE482A01020', true),
('TVSMOTOR', 'TVS Motor Company Ltd', 'Automobile', 'Automobile', 'INE494B01023', true)

ON DUPLICATE KEY UPDATE 
    company_name = VALUES(company_name),
    industry = VALUES(industry),
    sector = VALUES(sector),
    isin = VALUES(isin),
    is_active = VALUES(is_active);
