-- Insert NSE stocks into existing tables
-- Run this AFTER starting the backend (tables will be auto-created by JPA)

INSERT INTO stocks (symbol, company_name, industry, sector, isin, series, is_active) VALUES
-- Top 50 NSE Stocks
('RELIANCE', 'Reliance Industries Ltd', 'Refineries', 'Energy', 'INE002A01018', 'EQ', true),
('TCS', 'Tata Consultancy Services Ltd', 'IT Services & Consulting', 'Technology', 'INE467B01029', 'EQ', true),
('HDFCBANK', 'HDFC Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE040A01034', 'EQ', true),
('INFY', 'Infosys Ltd', 'IT Services & Consulting', 'Technology', 'INE009A01021', 'EQ', true),
('ICICIBANK', 'ICICI Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE090A01021', 'EQ', true),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'FMCG', 'Consumer Goods', 'INE030A01027', 'EQ', true),
('BHARTIARTL', 'Bharti Airtel Ltd', 'Telecom Services', 'Telecom', 'INE397D01024', 'EQ', true),
('SBIN', 'State Bank of India', 'Public Sector Bank', 'Financial Services', 'INE062A01020', 'EQ', true),
('LT', 'Larsen & Toubro Ltd', 'Engineering & Construction', 'Infrastructure', 'INE018A01030', 'EQ', true),
('ITC', 'ITC Ltd', 'FMCG', 'Consumer Goods', 'INE154A01025', 'EQ', true),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE237A01028', 'EQ', true),
('AXISBANK', 'Axis Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE238A01034', 'EQ', true),
('BAJFINANCE', 'Bajaj Finance Ltd', 'NBFC', 'Financial Services', 'INE296A01024', 'EQ', true),
('ASIANPAINT', 'Asian Paints Ltd', 'Paints', 'Consumer Goods', 'INE021A01026', 'EQ', true),
('MARUTI', 'Maruti Suzuki India Ltd', 'Automobile', 'Automobile', 'INE585B01010', 'EQ', true),
('HCLTECH', 'HCL Technologies Ltd', 'IT Services & Consulting', 'Technology', 'INE860A01027', 'EQ', true),
('WIPRO', 'Wipro Ltd', 'IT Services & Consulting', 'Technology', 'INE075A01022', 'EQ', true),
('TATAMOTORS', 'Tata Motors Ltd', 'Automobile', 'Automobile', 'INE155A01022', 'EQ', true),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'Pharmaceuticals', 'Healthcare', 'INE044A01036', 'EQ', true),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'Cement', 'Construction Materials', 'INE481G01011', 'EQ', true),
('TITAN', 'Titan Company Ltd', 'Gems & Jewellery', 'Consumer Goods', 'INE280A01028', 'EQ', true),
('NESTLEIND', 'Nestle India Ltd', 'FMCG', 'Consumer Goods', 'INE239A01024', 'EQ', true),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'Power Transmission', 'Utilities', 'INE752E01010', 'EQ', true),
('NTPC', 'NTPC Ltd', 'Power Generation', 'Utilities', 'INE733E01010', 'EQ', true),
('ONGC', 'Oil & Natural Gas Corporation Ltd', 'Oil Exploration', 'Energy', 'INE213A01029', 'EQ', true),
('ADANIENT', 'Adani Enterprises Ltd', 'Trading', 'Diversified', 'INE423A01024', 'EQ', true),
('ADANIPORTS', 'Adani Ports & Special Economic Zone Ltd', 'Port Services', 'Infrastructure', 'INE742F01042', 'EQ', true),
('COALINDIA', 'Coal India Ltd', 'Coal Mining', 'Energy', 'INE522F01014', 'EQ', true),
('JSWSTEEL', 'JSW Steel Ltd', 'Steel', 'Metals', 'INE019A01038', 'EQ', true),
('TATASTEEL', 'Tata Steel Ltd', 'Steel', 'Metals', 'INE081A01020', 'EQ', true),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'NBFC', 'Financial Services', 'INE918I01018', 'EQ', true),
('TECHM', 'Tech Mahindra Ltd', 'IT Services & Consulting', 'Technology', 'INE669C01036', 'EQ', true),
('DIVISLAB', 'Divi''s Laboratories Ltd', 'Pharmaceuticals', 'Healthcare', 'INE361B01024', 'EQ', true),
('M&M', 'Mahindra & Mahindra Ltd', 'Automobile', 'Automobile', 'INE101A01026', 'EQ', true),
('HINDALCO', 'Hindalco Industries Ltd', 'Aluminium', 'Metals', 'INE038A01020', 'EQ', true),
('EICHERMOT', 'Eicher Motors Ltd', 'Automobile', 'Automobile', 'INE066A01021', 'EQ', true),
('DRREDDY', 'Dr Reddy''s Laboratories Ltd', 'Pharmaceuticals', 'Healthcare', 'INE089A01023', 'EQ', true),
('BRITANNIA', 'Britannia Industries Ltd', 'FMCG', 'Consumer Goods', 'INE216A01030', 'EQ', true),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'Hospitals', 'Healthcare', 'INE437A01024', 'EQ', true),
('CIPLA', 'Cipla Ltd', 'Pharmaceuticals', 'Healthcare', 'INE059A01026', 'EQ', true),
('GRASIM', 'Grasim Industries Ltd', 'Cement & Textiles', 'Diversified', 'INE047A01021', 'EQ', true),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'Refineries', 'Energy', 'INE029A01011', 'EQ', true),
('INDUSINDBK', 'IndusInd Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE095A01012', 'EQ', true),
('SHREECEM', 'Shree Cement Ltd', 'Cement', 'Construction Materials', 'INE070A01015', 'EQ', true),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'Automobile', 'Automobile', 'INE158A01026', 'EQ', true),
('TATACONSUM', 'Tata Consumer Products Ltd', 'FMCG', 'Consumer Goods', 'INE192A01025', 'EQ', true),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'Automobile', 'Automobile', 'INE917I01010', 'EQ', true),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'Life Insurance', 'Financial Services', 'INE123W01016', 'EQ', true),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'Life Insurance', 'Financial Services', 'INE795G01014', 'EQ', true),
('TATAPOWER', 'Tata Power Company Ltd', 'Power Generation', 'Utilities', 'INE245A01021', 'EQ', true),

-- More NSE Stocks (Next 50)
('VEDL', 'Vedanta Ltd', 'Mining', 'Metals', 'INE205A01025', 'EQ', true),
('BANKBARODA', 'Bank of Baroda', 'Public Sector Bank', 'Financial Services', 'INE028A01039', 'EQ', true),
('PNB', 'Punjab National Bank', 'Public Sector Bank', 'Financial Services', 'INE160A01022', 'EQ', true),
('IOC', 'Indian Oil Corporation Ltd', 'Refineries', 'Energy', 'INE242A01010', 'EQ', true),
('GODREJCP', 'Godrej Consumer Products Ltd', 'FMCG', 'Consumer Goods', 'INE102D01028', 'EQ', true),
('DLF', 'DLF Ltd', 'Real Estate', 'Real Estate', 'INE271C01023', 'EQ', true),
('PIDILITIND', 'Pidilite Industries Ltd', 'Chemicals', 'Chemicals', 'INE318A01026', 'EQ', true),
('SIEMENS', 'Siemens Ltd', 'Engineering', 'Infrastructure', 'INE003A01024', 'EQ', true),
('ABB', 'ABB India Ltd', 'Engineering', 'Infrastructure', 'INE117A01022', 'EQ', true),
('BOSCHLTD', 'Bosch Ltd', 'Auto Components', 'Automobile', 'INE323A01026', 'EQ', true),
('AMBUJACEM', 'Ambuja Cements Ltd', 'Cement', 'Construction Materials', 'INE079A01024', 'EQ', true),
('ACC', 'ACC Ltd', 'Cement', 'Construction Materials', 'INE012A01025', 'EQ', true),
('GAIL', 'GAIL (India) Ltd', 'Gas Transmission', 'Energy', 'INE129A01019', 'EQ', true),
('INDIGO', 'InterGlobe Aviation Ltd', 'Airlines', 'Aviation', 'INE646L01027', 'EQ', true),
('HAVELLS', 'Havells India Ltd', 'Electricals', 'Consumer Goods', 'INE176B01034', 'EQ', true),
('LUPIN', 'Lupin Ltd', 'Pharmaceuticals', 'Healthcare', 'INE326A01037', 'EQ', true),
('MOTHERSON', 'Samvardhana Motherson International Ltd', 'Auto Components', 'Automobile', 'INE775A01035', 'EQ', true),
('BERGEPAINT', 'Berger Paints India Ltd', 'Paints', 'Consumer Goods', 'INE463A01038', 'EQ', true),
('MARICO', 'Marico Ltd', 'FMCG', 'Consumer Goods', 'INE196A01026', 'EQ', true),
('DABUR', 'Dabur India Ltd', 'FMCG', 'Consumer Goods', 'INE016A01026', 'EQ', true),
('COLPAL', 'Colgate-Palmolive (India) Ltd', 'FMCG', 'Consumer Goods', 'INE259A01022', 'EQ', true),
('MCDOWELL-N', 'United Spirits Ltd', 'Beverages', 'Consumer Goods', 'INE854D01024', 'EQ', true),
('UPL', 'UPL Ltd', 'Agrochemicals', 'Chemicals', 'INE628A01036', 'EQ', true),
('TORNTPHARM', 'Torrent Pharmaceuticals Ltd', 'Pharmaceuticals', 'Healthcare', 'INE685A01028', 'EQ', true),
('BIOCON', 'Biocon Ltd', 'Pharmaceuticals', 'Healthcare', 'INE376G01013', 'EQ', true),
('AUROPHARMA', 'Aurobindo Pharma Ltd', 'Pharmaceuticals', 'Healthcare', 'INE406A01037', 'EQ', true),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd', 'Pharmaceuticals', 'Healthcare', 'INE010B01027', 'EQ', true),
('PEL', 'Piramal Enterprises Ltd', 'Pharmaceuticals', 'Healthcare', 'INE140A01024', 'EQ', true),
('MUTHOOTFIN', 'Muthoot Finance Ltd', 'NBFC', 'Financial Services', 'INE414G01012', 'EQ', true),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'NBFC', 'Financial Services', 'INE115A01026', 'EQ', true),
('CHOLAFIN', 'Cholamandalam Investment and Finance Company Ltd', 'NBFC', 'Financial Services', 'INE121A01024', 'EQ', true),
('SBICARD', 'SBI Cards and Payment Services Ltd', 'NBFC', 'Financial Services', 'INE018E01016', 'EQ', true),
('BANDHANBNK', 'Bandhan Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE545U01014', 'EQ', true),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE092T01019', 'EQ', true),
('FEDERALBNK', 'Federal Bank Ltd', 'Private Sector Bank', 'Financial Services', 'INE171A01029', 'EQ', true),
('CANBK', 'Canara Bank', 'Public Sector Bank', 'Financial Services', 'INE476A01022', 'EQ', true),
('UNIONBANK', 'Union Bank of India', 'Public Sector Bank', 'Financial Services', 'INE692A01016', 'EQ', true),
('INDHOTEL', 'The Indian Hotels Company Ltd', 'Hotels', 'Hospitality', 'INE053A01029', 'EQ', true),
('BATAINDIA', 'Bata India Ltd', 'Footwear', 'Consumer Goods', 'INE176A01028', 'EQ', true),
('RELAXO', 'Relaxo Footwears Ltd', 'Footwear', 'Consumer Goods', 'INE131B01039', 'EQ', true),
('VOLTAS', 'Voltas Ltd', 'Consumer Durables', 'Consumer Goods', 'INE226A01021', 'EQ', true),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'Consumer Durables', 'Consumer Goods', 'INE716A01013', 'EQ', true),
('DIXON', 'Dixon Technologies (India) Ltd', 'Electronics', 'Consumer Goods', 'INE935N01012', 'EQ', true),
('AMARAJABAT', 'Amara Raja Batteries Ltd', 'Auto Components', 'Automobile', 'INE885A01032', 'EQ', true),
('EXIDEIND', 'Exide Industries Ltd', 'Auto Components', 'Automobile', 'INE302A01020', 'EQ', true),
('MRF', 'MRF Ltd', 'Tyres', 'Automobile', 'INE883A01011', 'EQ', true),
('APOLLOTYRE', 'Apollo Tyres Ltd', 'Tyres', 'Automobile', 'INE438A01022', 'EQ', true),
('CEATLTD', 'CEAT Ltd', 'Tyres', 'Automobile', 'INE482A01020', 'EQ', true),
('TVSMOTOR', 'TVS Motor Company Ltd', 'Automobile', 'Automobile', 'INE494B01023', 'EQ', true)

ON CONFLICT (symbol) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    industry = EXCLUDED.industry,
    sector = EXCLUDED.sector,
    isin = EXCLUDED.isin,
    is_active = EXCLUDED.is_active;
